version: "3.9"
services:
  nginx:
    build: .
    image: heartexlabs/label-studio:1.9.2
    restart: unless-stopped
    ports:
      - "9080:8085"
      - "9081:8086"
    depends_on:
      - app
    environment:
      - LABEL_STUDIO_HOST=${LABEL_STUDIO_HOST:-}
    #   Optional: Specify SSL termination certificate & key
    #   Just drop your cert.pem and cert.key into folder 'deploy/nginx/certs'
    #      - NGINX_SSL_CERT=/certs/cert.pem
    #      - NGINX_SSL_CERT_KEY=/certs/cert.key
    volumes:
      - /home/zhouli/docker/labeling_192/mydata:/label-studio/data:rw
      - /home/zhouli/labeling/label-studio/deploy/nginx/certs:/certs:ro
    #   Optional: Override nginx default conf
    #      - ./deploy/my.conf:/etc/nginx/nginx.conf
    command: nginx

  app:
    stdin_open: true
    tty: true
    build: .
    image: heartexlabs/label-studio:1.9.2
    restart: unless-stopped
    expose:
      - "8000"
    depends_on:
      - db
    environment:
      - DJANGO_DB=default
      - POSTGRE_NAME=postgres
      - POSTGRE_USER=postgres
      - POSTGRE_PASSWORD=
      - POSTGRE_PORT=5432
      - POSTGRE_HOST=db
      - LABEL_STUDIO_HOST=${LABEL_STUDIO_HOST:-}
      - JSON_LOG=1
      - LOG_LEVEL=DEBUG
      - MINIO_STORAGE_ACCESS_KEY=${MINIO_ROOT_USER:-minio_admin_do_not_use_in_production}
      - MINIO_STORAGE_SECRET_KEY=${MINIO_ROOT_PASSWORD:-minio_admin_do_not_use_in_production}
      - MINIO_STORAGE_BUCKET_NAME=data
      - MINIO_STORAGE_ENDPOINT=http://minio:9000
    volumes:
      - /home/zhouli/docker/labeling_192/mydata:/label-studio/data:rw
      - /home/zhouli/labeling/label-studio/deploy/uwsgi.ini:/label-studio/deploy/uwsgi.ini:rw
    command: label-studio-uwsgi

  db:
    image: postgres:11.5
    hostname: db
    restart: unless-stopped
    ports:
      - "5432:5432"
    # Optional: Enable TLS on PostgreSQL
    # Just drop your server.crt and server.key into folder 'deploy/pgsql/certs'
    # NOTE: Both files must have permissions u=rw (0600) or less
    #    command: >
    #      -c ssl=on
    #      -c ssl_cert_file=/var/lib/postgresql/certs/server.crt
    #      -c ssl_key_file=/var/lib/postgresql/certs/server.key
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - /home/zhouli/docker/labeling_192/postgres-data:/var/lib/postgresql/data
      - /home/zhouli/labeling/label-studio/deploy/pgsql/certs:/var/lib/postgresql/certs:ro

