version: "3.9"

# rotating logs so they do not overflow
x-logging:
  logging: &default-logging
    driver: "local"
    options:
      max-size: "10m"
      max-file: "3"

services:
  db:
    image: postgres:11.5
    hostname: db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - /home/zhouli/docker/labeling_192/postgres-data:/var/lib/postgresql/data
      - /home/zhouli/labeling/label-studio/deploy/pgsql/certs:/var/lib/postgresql/certs:ro

  # not replicated setup for test setup, use a proper aws S3 compatible cluster in production
  minio:
    image: quay.io/minio/minio:RELEASE.2023-03-13T19-46-17Z
    command: server /data --console-address ":9009"
    restart: unless-stopped
    logging: *default-logging
    ports:
      - "9000:9000"
      - "9009:9009"
    volumes:
      - /home/zhouli/docker/labeling_192/minio-data:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-label_minio}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-label_minio}
